name: CI
on:
  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: michaelleehobbs/opalapi
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and Push arm64 to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./Dockerfile.arm64v8
          repository: michaelleehobbs/opalapi
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/').arm64 }}
